synthesis:
  bit_stuck_error:
    regex: /WARNING\s-\ssynthesis. Bit (.+) is stuck at Zero/
    color: blue
    severity: low
    hide: yes
  truncation_error:
    regex: /truncated to fit/
    color: green
    severity: high
  bit_length_error:
    regex: /differs from formal bit length/
    color: magenta
    severity: low
  index_out_of_range_error:
    regex: /VERI-1216$/
    severity: low
    color: red
  localized_parameter_error:
    regex: /VERI-1199$/
    severity: low
    color: cyan
  usb_compilation:
    regex: /VERI-1018$/
    severity: moniter
    color: blue
  veri_analysis:
    regex: /VERI-1482$/
    severity: moniter
    color: cyan
  veri_default_warning:
    regex: /WARNING(.*)/
    severity: high
    color: red
    id: 1
  veri_error:
    regex: /(VERI-.+)/
    severity: low
    color: yellow
    id: 1
